"""Layer 4: everything the 3080 needs to train — and the promotion gate.

``train-kit`` reads a compiled dataset (Layer 3's ``sft_*.jsonl`` /
``dpo_*.jsonl``) and emits a ready-to-run training bundle for the RTX
3080 machine: an unsloth QLoRA script sized to the card and the dataset,
an Ollama ``Modelfile`` for serving the result, and a step-by-step
runbook. No training happens here — this box has no GPU; the kit is the
contract between the lab and the training machine.

``promote`` is the other half of the deal: a fine-tuned model only takes
a role in the engine when the scorecard PROVES it beats both the memory
baseline and the model it replaces, on the same question bank. The gate
is a rule, not a feeling.

Sizing defaults target an RTX 3080 (10 GB): 4-bit QLoRA on an 8B
instruct base, sequence length 1024, micro-batch 2 with gradient
accumulation. Epochs scale down as the dataset grows so small archives
do not overfit into parrots.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

DEFAULT_BASE_MODEL = "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"
MIN_EXAMPLES_TO_TRAIN = 50
MIN_PAIRS_FOR_DPO = 40


@dataclass
class TrainPlan:
    dataset_dir: str
    base_model: str
    sft_train: int
    sft_eval: int
    dpo_train: int
    dpo_eval: int
    epochs: int
    run_dpo: bool
    warnings: list[str]

    @property
    def ready(self) -> bool:
        return self.sft_train >= MIN_EXAMPLES_TO_TRAIN


def _count_lines(path: Path) -> int:
    if not path.exists():
        return 0
    with open(path, encoding="utf-8") as f:
        return sum(1 for line in f if line.strip())


def build_plan(dataset_dir: str | Path,
               *, base_model: str = DEFAULT_BASE_MODEL) -> TrainPlan:
    dataset = Path(dataset_dir)
    sft_train = _count_lines(dataset / "sft_train.jsonl")
    sft_eval = _count_lines(dataset / "sft_eval.jsonl")
    dpo_train = _count_lines(dataset / "dpo_train.jsonl")
    dpo_eval = _count_lines(dataset / "dpo_eval.jsonl")

    # Small archives need repetition; large ones need restraint.
    if sft_train < 200:
        epochs = 4
    elif sft_train < 1000:
        epochs = 3
    else:
        epochs = 2

    warnings: list[str] = []
    if sft_train < MIN_EXAMPLES_TO_TRAIN:
        warnings.append(
            f"only {sft_train} SFT examples — below the {MIN_EXAMPLES_TO_TRAIN}"
            " floor; collect more human decisions before burning GPU hours")
    if sft_eval == 0:
        warnings.append("no SFT eval examples — the split has nothing to "
                        "measure with; do not train on this")
    run_dpo = dpo_train >= MIN_PAIRS_FOR_DPO
    if 0 < dpo_train < MIN_PAIRS_FOR_DPO:
        warnings.append(
            f"{dpo_train} DPO pair(s) is too few to shape preferences "
            f"(floor {MIN_PAIRS_FOR_DPO}); DPO stage disabled for now")
    return TrainPlan(
        dataset_dir=str(dataset), base_model=base_model,
        sft_train=sft_train, sft_eval=sft_eval,
        dpo_train=dpo_train, dpo_eval=dpo_eval,
        epochs=epochs, run_dpo=run_dpo, warnings=warnings,
    )


# ---------------------------------------------------------------------------
# Rendered artifacts
# ---------------------------------------------------------------------------

def render_unsloth_script(plan: TrainPlan, *, model_name: str) -> str:
    dpo_block = f'''
# ---- Stage 2: DPO on human preference pairs ({plan.dpo_train} pairs) ----
from trl import DPOConfig, DPOTrainer

dpo_dataset = load_dataset("json", data_files={{
    "train": str(DATASET / "dpo_train.jsonl"),
    "eval": str(DATASET / "dpo_eval.jsonl"),
}})

dpo_trainer = DPOTrainer(
    model=model,
    args=DPOConfig(
        output_dir=str(OUT / "dpo"),
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=1,
        learning_rate=5e-6,
        beta=0.1,
        max_length=1024,
        logging_steps=5,
        bf16=False, fp16=True,
    ),
    train_dataset=dpo_dataset["train"],
    eval_dataset=dpo_dataset["eval"],
    processing_class=tokenizer,
)
dpo_trainer.train()
''' if plan.run_dpo else "\n# DPO stage disabled: not enough preference pairs yet.\n"

    return f'''#!/usr/bin/env python3
"""QLoRA fine-tune for the campaign engine — generated by `lab train-kit`.

Run ON THE 3080 MACHINE (needs CUDA):
    pip install unsloth trl datasets
    python train_{model_name}.py
"""
from pathlib import Path

from datasets import load_dataset
from unsloth import FastLanguageModel

DATASET = Path({json.dumps(plan.dataset_dir)})
OUT = Path("runs/{model_name}")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name={json.dumps(plan.base_model)},
    max_seq_length=1024,
    load_in_4bit=True,
)
model = FastLanguageModel.get_peft_model(
    model, r=16, lora_alpha=32, lora_dropout=0.0,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
)

dataset = load_dataset("json", data_files={{
    "train": str(DATASET / "sft_train.jsonl"),
    "eval": str(DATASET / "sft_eval.jsonl"),
}})

def to_text(row):
    return {{"text": tokenizer.apply_chat_template(
        row["messages"], tokenize=False, add_generation_prompt=False)}}

dataset = dataset.map(to_text)

from trl import SFTConfig, SFTTrainer

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["eval"],
    dataset_text_field="text",
    args=SFTConfig(
        output_dir=str(OUT / "sft"),
        per_device_train_batch_size=2,
        gradient_accumulation_steps=8,
        num_train_epochs={plan.epochs},
        learning_rate=2e-4,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        logging_steps=5,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        max_seq_length=1024,
        bf16=False, fp16=True,
        seed=3407,
    ),
)
trainer.train()
{dpo_block}
# ---- Export: GGUF for Ollama on this same machine ----
model.save_pretrained_gguf(str(OUT / "gguf"), tokenizer,
                           quantization_method="q4_k_m")
print("GGUF written to", OUT / "gguf")
print("next: ollama create {model_name} -f Modelfile && ollama serve")
'''


def render_modelfile(plan: TrainPlan, *, model_name: str) -> str:
    return f'''# Ollama Modelfile — generated by `lab train-kit`
# ollama create {model_name} -f Modelfile
FROM ./runs/{model_name}/gguf/unsloth.Q4_K_M.gguf
PARAMETER temperature 0
PARAMETER num_ctx 4096
SYSTEM """You answer questions about one D&D campaign using only the campaign record provided. If the record does not contain the answer, reply exactly: not in the record"""
'''


def render_runbook(plan: TrainPlan, *, model_name: str) -> str:
    ready = ("READY — the dataset clears the floor."
             if plan.ready else
             "NOT READY — see warnings; collect more decisions first.")
    warning_lines = "".join(f"\n> - {w}" for w in plan.warnings) or "\n> - none"
    return f'''# Train kit — {model_name}

**Dataset:** `{plan.dataset_dir}` — {plan.sft_train} SFT train / {plan.sft_eval} eval,
{plan.dpo_train} DPO train / {plan.dpo_eval} eval. **{ready}**

> Warnings:{warning_lines}

## On the 3080 machine

1. `pip install unsloth trl datasets` (once; needs CUDA)
2. `python train_{model_name}.py` — SFT{" then DPO" if plan.run_dpo else ""},
   ~{plan.epochs} epochs, fits in 10 GB at 4-bit.
3. `ollama create {model_name} -f Modelfile && ollama serve`
   (expose it on your LAN: `OLLAMA_HOST=0.0.0.0 ollama serve`)

## Back on the main PC — prove it before it serves

```powershell
$env:TEACHERS = "local:{model_name}"
$env:LOCAL_AI_BASE_URL = "http://<3080-ip>:11434/v1"
python -m transcripts_ai.lab score --db <db> --campaign <campaign> `
    --bank bank.jsonl --answerer teacher:local --history history.jsonl
python -m transcripts_ai.lab promote --history history.jsonl `
    --candidate "teacher:local:{model_name}" --baseline memory-baseline
```

`promote` exits 0 only when the model beats the memory baseline (and its
own previous version, when one exists) on the same bank. Only then point
an engine role at it, e.g. `AI_ROLE_ANSWERER=local:{model_name}`.
'''


def write_train_kit(plan: TrainPlan, out_dir: str | Path,
                    *, model_name: str) -> list[str]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    files = {
        f"train_{model_name}.py": render_unsloth_script(plan, model_name=model_name),
        "Modelfile": render_modelfile(plan, model_name=model_name),
        "TRAIN_RUNBOOK.md": render_runbook(plan, model_name=model_name),
    }
    for name, content in files.items():
        (out / name).write_text(content, encoding="utf-8")
    return sorted(files)


# ---------------------------------------------------------------------------
# The promotion gate
# ---------------------------------------------------------------------------

@dataclass
class PromotionVerdict:
    promote: bool
    reasons: list[str]


def promotion_verdict(
    history: list[dict],
    *,
    candidate: str,
    baseline: str,
    min_lead: float = 0.02,
) -> PromotionVerdict:
    """Does the candidate's latest run earn a role?

    Rules, in order: the candidate must have a run; the baseline must
    have a run on the SAME bank size (otherwise the comparison is
    meaningless and the gate refuses rather than guesses); the candidate
    must beat the baseline by ``min_lead`` accuracy; and if the candidate
    has an earlier run on the same bank size, it must not have regressed.
    """
    def latest(name: str) -> list[dict]:
        return [h for h in history if h.get("answerer") == name]

    def accuracy(entry: dict) -> float:
        return entry["correct"] / entry["total"] if entry["total"] else 0.0

    reasons: list[str] = []
    candidate_runs = latest(candidate)
    baseline_runs = latest(baseline)
    if not candidate_runs:
        return PromotionVerdict(False, [f"no scorecard runs for {candidate!r}"])
    newest = candidate_runs[-1]
    comparable = [b for b in baseline_runs if b["total"] == newest["total"]]
    if not comparable:
        return PromotionVerdict(False, [
            f"no {baseline!r} run on the same bank size "
            f"({newest['total']} questions) — run the baseline first"])
    base = comparable[-1]
    lead = accuracy(newest) - accuracy(base)
    if lead < min_lead:
        reasons.append(
            f"candidate {accuracy(newest):.1%} vs baseline {accuracy(base):.1%}"
            f" — lead {lead:+.1%} is under the {min_lead:.0%} bar")
    previous = [c for c in candidate_runs[:-1] if c["total"] == newest["total"]]
    if previous and accuracy(newest) < accuracy(previous[-1]):
        reasons.append(
            f"regressed vs its own previous run "
            f"({accuracy(newest):.1%} < {accuracy(previous[-1]):.1%})")
    if reasons:
        return PromotionVerdict(False, reasons)
    return PromotionVerdict(True, [
        f"beats baseline by {lead:+.1%} on {newest['total']} questions"
        + (" and improved on its previous run" if previous else "")])
